

;Zeitzone
date.timezone = Europe/Berlin

; Maximale Ausführungszeit pro Request (in Sekunden)
max_execution_time = 30

; Zeichenkodierung
default_charset = "UTF-8"

; Fehler NUR ins Log schreiben – niemals im Browser anzeigen
display_errors = Off
log_errors = On
error_log = /var/log/apache2/php_errors.log